dist: xenial
language: python
python: 3.7

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: poetry install

script:
  - make test
  - sh 'bin/homework1.sh'

notifications:
  email:
    on_success: never
    on_failure: change
