# -*- coding: utf-8 -*-

"""
Django settings for piepizza project.

Generated by 'django-admin startproject' using Django 1.11.25.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # noqa WPS221


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '{0}{1}{2}'.format(
    '4#5rmuu3kk%mx(yx9',
    '=-j!e4wr=l&+$22',
    '6065jt)!_-qdt^pa%p',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # noqa WPS407


# Application definition

INSTALLED_APPS = [  # noqa WPS407
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [  # noqa WPS407
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'piepizza.urls'  # noqa WPS407

TEMPLATES = [  # noqa WPS407
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'piepizza.wsgi.application'  # noqa WPS407


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
name = 'NAME'
DATABASES = {  # noqa WPS407
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        name: os.path.join(BASE_DIR, 'db.sqlite3'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

base_django_auth = 'django.contrib.auth.'
format_template = '{0}{1}'
AUTH_PASSWORD_VALIDATORS = [  # noqa WPS407
    {
        name: format_template.format(
            base_django_auth,
            'password_validation.UserAttributeSimilarityValidator',
        ),
    },
    {
        name: format_template.format(
            base_django_auth,
            'password_validation.MinimumLengthValidator',
        ),
    },
    {
        name: format_template.format(
            base_django_auth,
            'password_validation.CommonPasswordValidator',
        ),
    },
    {
        name: format_template.format(
            base_django_auth,
            'password_validation.NumericPasswordValidator',
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
