# Generated by Django 2.0.1 on 2019-10-28 18:47

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_date', models.DateField(default=datetime.date.today)),
                ('delivery_address', models.CharField(max_length=128)),
                ('customer_email', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[(main.models.OrderType('ACCEPTED'), 'ACCEPTED'), (main.models.OrderType('COOKING'), 'COOKING'), (main.models.OrderType('DELIVERY'), 'DELIVERY'), (main.models.OrderType('COMPLETED'), 'COMPLETED')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='main.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='main.Pizza'),
        ),
    ]
