# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(main.models.OrderType('ACCEPTED'), 'ACCEPTED'), (main.models.OrderType('COOKING'), 'COOKING'), (main.models.OrderType('DELIVERY'), 'DELIVERY'), (main.models.OrderType('COMPLETED'), 'COMPLETED')], max_length=16),
        ),
    ]
