# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191029_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('COOKING', 'COOKING'), ('DELIVERY', 'DELIVERY'), ('COMPLETED', 'COMPLETED')], max_length=16),
        ),
    ]
